// game.js — Screen management, robust image loading, catch/release, XP, profile

window.currentUserEmail = null;
window.totalXP   = 0;
window.catchLog  = [];
window.currentFish = null;

const XP_PER_LEVEL = 100;
const RANK_TITLES  = [
  [0,   "BEGINNER ANGLER"],
  [100, "JUNIOR ANGLER"],
  [300, "SKILLED ANGLER"],
  [600, "EXPERT ANGLER"],
  [1000,"MASTER ANGLER"],
  [2000,"LEGENDARY ANGLER"],
];

// ── Screen manager ────────────────────────────────────────────────
function showScreen(id) {
  document.querySelectorAll(".screen").forEach(s => s.classList.remove("active"));
  const el = document.getElementById(id);
  if (el) el.classList.add("active");
}

// ── Auth guard ────────────────────────────────────────────────────
function requireAuth(then) {
  if (!window.currentUserEmail) { showScreen("screen-home"); return false; }
  if (then) then();
  return true;
}

// ══════════════════════════════════════════════════════════════════
//  ROBUST IMAGE LOADING
//  Tries each URL in fish.imgs[] in order.
//  If all fail → uses SVG illustration generated by makeFishSVG().
// ══════════════════════════════════════════════════════════════════

/**
 * loadFishImage(fish, imgEl)
 * Tries fish.imgs[0], then [1], then [2], then SVG fallback.
 * Shows a shimmer placeholder while loading.
 */
function loadFishImage(fish, imgEl) {
  if (!imgEl) return;

  // Show shimmer while loading
  imgEl.classList.add("img-loading");
  imgEl.style.display = "";

  const sources = (fish.imgs || []).filter(Boolean);

  function tryNext(index) {
    if (index >= sources.length) {
      // All real images failed — use SVG illustration
      imgEl.src = makeFishSVG(fish);
      imgEl.classList.remove("img-loading");
      imgEl.onerror = null;
      return;
    }

    const testImg = new Image();
    testImg.onload = () => {
      imgEl.src = sources[index];
      imgEl.classList.remove("img-loading");
      imgEl.onerror = () => tryNext(index + 1); // if it breaks later, try next
    };
    testImg.onerror = () => tryNext(index + 1);
    // Add cache-busting only on retry to avoid re-serving a cached 403
    testImg.src = index === 0 ? sources[index] : sources[index] + "?v=" + index;
    // Timeout: if no response in 5s, move on
    setTimeout(() => { if (!testImg.complete) tryNext(index + 1); }, 5000);
  }

  tryNext(0);
}

// ── Start AR ──────────────────────────────────────────────────────
function showARcast() {
  if (!requireAuth()) return;
  showScreen("screen-ar");
  if (typeof refreshARWeather === "function") refreshARWeather();
  setTimeout(() => startAR(), 150);
}

// ── Fish caught callback (from ar-scene.js) ───────────────────────
window.onFishReeled = function () {
  window.currentFish = getRandomFish();
  populateCatchScreen(window.currentFish);

  const catchBg = document.getElementById("catch-bg");
  const arVideo = document.getElementById("ar-video");
  if (catchBg && arVideo && arVideo.srcObject) {
    catchBg.srcObject = arVideo.srcObject;
    catchBg.play().catch(() => {});
  }

  showScreen("screen-catch");
};

// ── Populate catch card ───────────────────────────────────────────
function populateCatchScreen(fish) {
  const imgEl = document.getElementById("caught-fish-img");
  loadFishImage(fish, imgEl);

  setText("caught-name",    fish.name);
  setText("catch-xp-text",  "+" + fish.xp + " XP");
  setText("catch-fun-fact", "🎣 " + fish.funFact);

  const badgeEl = document.getElementById("catch-badge");
  if (badgeEl) {
    badgeEl.textContent = fish.badge;
    badgeEl.style.background = fish.badgeColor || "var(--blue)";
  }
}

// ── Open fish detail ──────────────────────────────────────────────
function openFishDetail() {
  if (!window.currentFish) return;
  populateFishDetail(window.currentFish);
  showScreen("screen-fish-detail");
}

function populateFishDetail(fish) {
  const photo = document.getElementById("detail-photo-img");
  loadFishImage(fish, photo);

  setText("detail-title",    fish.name);
  setText("d-sci",           fish.scientific);
  setText("d-size",          fish.size);
  setText("d-location",      fish.location);
  setText("d-conservation",  fish.conservation);
  setText("d-desc",          fish.description);
  setText("d-why",           fish.why);

  const badgeEl = document.getElementById("detail-badge");
  if (badgeEl) {
    badgeEl.textContent = fish.badge;
    badgeEl.style.background = fish.badgeColor || "var(--blue)";
  }
}

function setText(id, value) {
  const el = document.getElementById(id);
  if (el) el.textContent = value || "";
}

// ── Keep / Release ────────────────────────────────────────────────
function keepFish() {
  if (!window.currentFish) return;
  logCatch(window.currentFish, "KEPT");
  awardXP(window.currentFish.xp);
  window.currentFish = null;
  if (typeof persistCurrentUserData === "function") persistCurrentUserData();
  showScreen("screen-main");
}

function releaseFish() {
  if (!window.currentFish) return;
  logCatch(window.currentFish, "RELEASED");
  awardXP(Math.round(window.currentFish.xp * 1.25));
  window.currentFish = null;
  if (typeof persistCurrentUserData === "function") persistCurrentUserData();
  showScreen("screen-main");
}

// ── XP ────────────────────────────────────────────────────────────
function awardXP(amount) {
  window.totalXP = (window.totalXP || 0) + amount;
  updateXPDisplay();
}

function updateXPDisplay() {
  const xp    = window.totalXP || 0;
  const lvlXP = xp % XP_PER_LEVEL;
  const pct   = (lvlXP / XP_PER_LEVEL) * 100;

  const fill = document.getElementById("xp-fill");
  const cur  = document.getElementById("xp-cur");
  if (fill) fill.style.width = pct + "%";
  if (cur)  cur.textContent  = xp;

  let rank = RANK_TITLES[0][1];
  for (const [threshold, title] of RANK_TITLES) { if (xp >= threshold) rank = title; }
  const rankEl = document.getElementById("angler-rank");
  if (rankEl) rankEl.textContent = rank;
}

// ── Catch log ─────────────────────────────────────────────────────
function logCatch(fish, action) {
  window.catchLog = window.catchLog || [];
  window.catchLog.unshift({
    fishId: fish.id,
    name:   fish.name,
    imgs:   fish.imgs,
    svgColor: fish.svgColor,
    svgAccent: fish.svgAccent,
    badge:  fish.badge,
    color:  fish.badgeColor,
    xp:     fish.xp,
    action,
    time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    date: new Date().toLocaleDateString([], { month: "short", day: "numeric" })
  });
  renderCatchLog();
}

function renderCatchLog() {
  const list = document.getElementById("log-list");
  if (!list) return;
  const log = window.catchLog || [];
  if (log.length === 0) {
    list.innerHTML = '<p class="log-empty">No catches yet — go fish! 🎣</p>';
    return;
  }
  list.innerHTML = log.map((e, i) => `
    <div class="log-item" onclick="viewLogEntry(${i})">
      <div class="log-img-wrap">
        <img class="log-fish-photo" 
             src="" 
             alt="${e.name}"
             data-fish-index="${i}">
      </div>
      <div class="log-fish-info">
        <div class="log-fish-name">${e.name}</div>
        <div class="log-fish-meta">${e.date} · ${e.time} · +${e.xp} XP</div>
      </div>
      <div class="log-action ${e.action === 'KEPT' ? 'log-kept' : 'log-released'}">${e.action}</div>
    </div>`).join("");

  // Load images for each log item after render
  log.forEach((e, i) => {
    const imgEl = list.querySelector(`img[data-fish-index="${i}"]`);
    if (!imgEl) return;
    const fishLike = { imgs: e.imgs || [], svgColor: e.svgColor, svgAccent: e.svgAccent, name: e.name, id: e.fishId };
    loadFishImage(fishLike, imgEl);
  });
}

function viewLogEntry(index) {
  const entry = (window.catchLog || [])[index];
  if (!entry) return;
  const fish = FISH_DATABASE.find(f => f.id === entry.fishId);
  if (fish) {
    window.currentFish = fish;
    populateFishDetail(fish);
    const backBtn = document.querySelector("#screen-fish-detail .back-arrow");
    if (backBtn) backBtn.setAttribute("onclick", "showScreen('screen-profile')");
    showScreen("screen-fish-detail");
  }
}
